# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_cms.cms_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_api', '0002_auto_20171208_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(default=django_cms.cms_api.models.fancy_id_generator, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='id',
            field=models.CharField(default=django_cms.cms_api.models.fancy_id_generator, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default=django_cms.cms_api.models.fancy_id_generator, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=django_cms.cms_api.models.fancy_id_generator, max_length=8, primary_key=True, serialize=False),
        ),
    ]
